#if DEBUG
import Foundation

enum VoiceBenchmarkCorpus {
    static let samples: [String] = [
        "A quiet paragraph should flow naturally. The second sentence should not restart the voice.",
        "useEffect runs after React commits the rendered output to the DOM.",
        "useMemo caches a calculated value between renders.",
        "useCallback preserves a function reference when dependencies stay equal.",
        "React reconciliation compares descriptions of the user interface.",
        "A microtask runs after the current script completes.",
        "Promise.all waits for every promise in the input array.",
        "const values = await Promise.all(tasks);",
        "The === operator checks strict equality; == allows coercion.",
        "Use !== when testing strict inequality.",
        "The expression count++ increments count.",
        "A closure preserves access to its lexical environment.",
        "TypeScript uses a union such as string | number.",
        "Promise<User[]> describes a promise of an array of users.",
        "Record<string, boolean> maps string keys to boolean values.",
        "Optional chaining uses user?.profile?.name.",
        "Nullish coalescing uses value ?? fallback.",
        "A readonly field cannot be reassigned through that type.",
        "HTTP 200 indicates success; HTTP 404 indicates a missing resource.",
        "HTTP 429 asks the client to slow down.",
        "HTTPS protects HTTP traffic using TLS.",
        "Cache-Control: max-age=3600 permits an hour of freshness.",
        "An ETag identifies a version of a representation.",
        "GET retrieves a resource; POST submits data.",
        "A REST API can return a JSON response.",
        "The URL is https://example.com/api/v2/users?id=42.",
        "Open /usr/local/bin and inspect config.json.",
        "The Windows path is C:\\Users\\Reader\\notes.pdf.",
        "SQL indexes can avoid a full table scan.",
        "SELECT id, name FROM users WHERE active = true;",
        "PostgreSQL uses MVCC for concurrent access.",
        "A transaction commits atomically or rolls back.",
        "A deadlock occurs when transactions wait on each other's locks.",
        "Prepared statements prevent SQL injection through parameterization.",
        "OAuth delegates authorization; authentication verifies identity.",
        "JWT, CSRF, XSS, SQL, API, HTTP and DNS are distinct abbreviations.",
        "TCP retransmits missing segments.",
        "UDP sends datagrams without a delivery guarantee.",
        "DNS translates host names into addresses.",
        "IPv4 uses 32-bit addresses; IPv6 uses 128-bit addresses.",
        "Binary search runs in O(log n).",
        "Linear search takes O(n) time in the worst case.",
        "A nested loop may perform O(n²) operations.",
        "Merge sort takes O(n log n) time.",
        "A queue removes items in FIFO order.",
        "A stack removes items in LIFO order.",
        "Compare camelCase, PascalCase and snake_case identifiers.",
        "The function getUserByID returns a UserProfile.",
        "CSS grid controls rows and columns.",
        "Flexbox distributes space along a main axis.",
        "Node.js schedules asynchronous callbacks through its event loop.",
        "The browser parses HTML and builds the DOM.",
        "A cache invalidation message may arrive after a write.",
        "A retry needs an idempotency key to avoid duplicate effects.",
        "At 1.25 times speed, punctuation should remain understandable.",
        "Unicode matters: naïve, café, résumé, λ, π, and the emoji 🙂."
    ]
}
#endif
