import Foundation

/// Curated, auditable vocabulary for comparing a learner's wording with source wording.
/// Families are paraphrase *evidence*, not proof of entailment; every use is labelled
/// as lexical in the diagnosis it produces. Keep entries general to technical prose.
enum LexiconTables {
    /// Surface words that express the same relation in explanatory technical prose.
    static let families: [[String]] = [
        ["help", "let", "allow", "enable", "permit", "empower"],
        ["prevent", "stop", "block", "avoid", "protect", "guard", "forbid", "prohibit", "disallow", "shield", "stops"],
        ["repeat", "redo", "rerun", "again", "repeatedly", "twice", "duplicate", "retry"],
        ["reduce", "lower", "decrease", "cut", "lessen", "shrink", "minimize", "fewer", "less"],
        ["increase", "raise", "grow", "boost", "more", "higher", "greater", "rise", "expand"],
        ["fast", "quick", "quickly", "rapid", "speedy", "accelerate", "faster", "quicker", "efficient", "efficiently", "cheap"],
        ["slow", "slower", "sluggish", "costly", "expensive", "heavy"],
        ["create", "make", "generate", "build", "produce", "construct", "introduce", "form"],
        ["remove", "delete", "drop", "clear", "discard", "erase", "evict", "purge"],
        ["update", "change", "modify", "mutate", "alter", "edit", "set", "rewrite"],
        ["keep", "retain", "preserve", "hold", "maintain", "remember", "persist", "save", "store", "storage", "stay"],
        ["access", "read", "reach", "see", "view", "visible", "fetch", "receive", "remember"],
        ["match", "recognize", "recognise", "identify", "identity", "track", "distinguish", "tell", "know", "pinpoint", "locate", "find"],
        ["stale", "outdated", "old", "obsolete", "wrong", "incorrect", "inaccurate"],
        ["copy", "duplicate", "clone", "replica", "representation", "version", "snapshot"],
        ["request", "ask", "call", "invoke", "trigger", "fire", "run", "execute", "perform", "initiate", "schedule"],
        ["render", "rerender", "draw", "display", "paint", "show", "present", "screen", "interface", "ui"],
        ["fail", "failure", "error", "fault", "crash", "reject", "rejection", "break", "broken", "bug", "defect", "problem"],
        ["succeed", "success", "successful", "fulfil", "fulfill", "fulfillment", "fulfilment", "resolve", "result", "outcome", "complete", "work"],
        ["verify", "verification", "check", "validate", "validation", "confirm", "prove", "authenticate", "authentication", "test"],
        ["decide", "determine", "choose", "pick", "select", "settle", "govern", "control", "regulate", "manage", "rule", "check", "detect", "figure"],
        ["permission", "allowed", "authorize", "authorization", "authorise", "entitle", "right"],
        ["group", "bundle", "batch", "combine", "together", "collection", "set", "unit", "whole", "single", "atomic"],
        ["distribute", "spread", "balance", "share", "split", "divide", "across", "geographic", "geographically", "global", "world", "worldwide"],
        ["multiple", "several", "many", "various", "lot", "lots", "numerous", "huge", "large", "big", "massive", "enormous"],
        ["immediate", "immediately", "instant", "instantly", "now", "straightaway"],
        ["wait", "delay", "pause", "defer", "postpone", "until", "later", "latency", "lag"],
        ["quiet", "stop", "idle", "settle", "inactive", "inactivity", "silence", "calm"],
        ["limit", "cap", "restrict", "bound", "ceiling", "throttle", "most", "maximum"],
        ["temporary", "transient", "brief", "momentary", "intermittent"],
        ["try", "attempt", "retry"],
        ["near", "close", "nearby", "local", "closest", "edge", "proximity"],
        ["server", "backend", "origin", "host", "instance", "node", "machine"],
        ["content", "file", "asset", "resource", "static", "data"],
        ["traffic", "load", "request", "workload", "demand"],
        ["improve", "enhance", "better", "boost", "strengthen"],
        ["transform", "transformation", "convert", "turn", "map", "translate", "encode"],
        ["reverse", "reversible", "undo", "recover", "decrypt", "revert", "back", "invert"],
        ["partial", "half", "incomplete", "part", "portion", "fragment"],
        ["commit", "persist", "save", "apply", "finalize"],
        ["rollback", "undo", "revert", "abort", "cancel"],
        ["concurrent", "concurrently", "parallel", "simultaneous", "simultaneously", "overlap", "overlapping", "interleave", "interleaving"],
        ["timing", "order", "ordering", "interleaving", "sequence", "schedule"],
        ["need", "require", "requirement", "depend", "dependency", "rely", "want"],
        ["stuck", "deadlock", "hang", "freeze", "blocked"],
        ["operation", "action", "step", "write", "task", "job", "work"],
        ["key", "identifier", "id"],
        ["row", "record", "entry", "tuple", "item", "element"],
        ["link", "connect", "reference", "referential", "point", "associate", "relate", "related", "tie", "relationship", "join"],
        ["integrity", "valid", "consistent", "consistency", "correct", "correctness", "sound"],
        ["lookup", "search", "find", "query", "retrieval", "retrieve", "read"],
        ["particular", "certain", "specific", "some", "given", "chosen"],
        ["scan", "traverse", "iterate", "inspect", "examine"],
        ["listener", "handler", "callback", "subscriber"],
        ["ancestor", "parent", "container", "outer", "enclose", "enclosing"],
        ["descendant", "child", "children", "inner", "nested"],
        ["handle", "process", "deal", "manage", "catch"],
        ["url", "address", "path", "endpoint", "route", "link"],
        ["append", "add", "attach", "put", "place", "include"],
        ["dynamic", "variable", "changing", "placeholder", "parameter"],
        ["segment", "part", "piece", "portion", "section", "component"],
        ["unique", "uniquely", "distinct"],
        ["effect", "result", "outcome", "impact", "consequence"],
        ["same", "identical", "equal", "equivalent", "unchanged"],
        ["different", "distinct", "separate", "independent", "own", "other", "another", "individual"],
        ["once", "single"],
        ["window", "interval", "period", "span", "timeframe", "duration"],
        ["event", "keystroke", "input", "signal", "interaction", "click"],
        ["depend", "rely", "hinge"],
        ["represent", "stand", "model", "describe", "express", "denote"],
        ["eventual", "eventually", "future", "later", "pending"],
        ["asynchronous", "async"],
        ["synchronous", "sync", "blocking"],
        ["encrypt", "encrypted", "encryption", "cipher", "secret", "confidential", "hidden", "hide"],
        ["sign", "signed", "signature", "stamp"],
        ["issue", "issuer", "sign", "create", "mint"],
        ["origin", "domain", "site", "host", "website"],
        ["policy", "rule", "mechanism", "restriction", "constraint"],
        ["enforce", "apply", "impose"],
        ["grow", "scale", "increase", "expand"],
        ["exact", "exactly", "precise", "precisely", "specific"],
        ["predict", "tell", "estimate", "forecast", "measure"],
        ["device", "machine", "phone", "computer", "hardware"],
        ["contract", "interface", "protocol", "abstraction"],
        ["supply", "provide", "give", "inject", "pass", "offer"],
        ["coordinate", "orchestrate", "direct", "drive", "run"],
        ["difficult", "hard", "tricky", "complicated", "complex"],
        ["easy", "simple", "simpler", "straightforward", "trivial"],
        ["variable", "binding", "environment", "scope", "context"],
        ["function", "callback", "closure", "method"],
        ["finish", "return", "complete", "end", "exit", "done"],
        ["whole", "entire", "complete", "full", "all"],
        ["automatic", "automatically", "implicit", "implicitly"],
        ["explicit", "explicitly", "manual", "manually", "yourself"],
        ["poor", "bad", "wrong", "problematic", "unsafe", "risky"],
        ["fine", "good", "safe", "okay", "ok", "great", "acceptable"],
        ["stable", "consistent", "persistent", "fixed", "permanent"],
        ["random", "unstable", "arbitrary", "changing", "fresh", "freshly"],
        ["continuity", "continuation", "continuous"],
        ["lose", "lost", "destroy", "break", "discard", "wipe", "reset"],
        ["inherit", "take", "receive", "acquire", "adopt", "transfer"],
        ["expression", "value", "result"],
        ["block", "brace", "braces"],
        ["composition", "compose", "assemble", "wire", "wiring"],
        ["test", "tests", "testing", "double", "mock", "stub"]
    ]

    /// Bipolar dimensions. Two wordings on opposite poles of one dimension disagree.
    static let dimensions: [(String, [String], [String])] = [
        ("speed", ["fast", "faster", "quick", "quicker", "quickly", "speedy", "accelerate", "efficient", "efficiently"], ["slow", "slower", "sluggish", "inefficient"]),
        ("amount", ["increase", "raise", "grow", "boost", "more", "higher", "greater"], ["reduce", "lower", "decrease", "cut", "lessen", "less", "fewer", "minimize"]),
        ("sameness", ["same", "identical", "shared", "share", "equal", "common"], ["different", "separate", "independent", "distinct", "own", "individual", "another", "other"]),
        ("retention", ["keep", "preserve", "retain", "maintain", "persist"], ["destroy", "break", "lose", "lost", "discard", "wipe", "reset"]),
        ("possession", ["inherit", "acquire", "receive", "takeover"], ["keep", "retain", "own"]),
        ("reversibility", ["reversible", "recoverable", "undoable", "decrypt", "back"], ["one-way", "irreversible", "unrecoverable", "oneway"]),
        ("state", ["stateless"], ["stateful"]),
        ("timing", ["immediate", "immediately", "instant", "instantly"], ["wait", "delay", "defer", "postpone"]),
        ("explicitness", ["explicit", "explicitly", "manual", "manually", "yourself"], ["automatic", "automatically", "implicit", "implicitly"]),
        ("quality", ["poor", "bad", "unsafe", "risky", "wrong", "problematic"], ["fine", "good", "safe", "okay", "ok", "great", "acceptable", "correct"]),
        ("stability", ["stable", "fixed", "persistent", "permanent"], ["random", "unstable", "arbitrary", "freshly", "fresh"]),
        ("difficulty", ["difficult", "hard", "harder", "tricky", "complicated"], ["easy", "easier", "simple", "simpler", "straightforward"]),
        ("validity", ["valid", "consistent", "correct", "intact"], ["invalid", "inconsistent", "corrupt", "corrupted", "broken"]),
        ("completeness", ["complete", "whole", "entire", "full", "all"], ["partial", "half", "incomplete"]),
        ("cardinality", ["multiple", "many", "several", "across", "various"], ["single", "sole"]),
        ("encryption", ["encrypted", "encrypt", "confidential", "hidden", "secret"], ["plaintext", "unencrypted", "readable", "decoded"]),
        ("activity", ["continue", "ongoing"], ["stop", "quiet", "idle", "inactivity"]),
        ("outcome", ["success", "succeed", "fulfillment", "fulfil", "fulfill", "resolve"], ["failure", "fail", "rejection", "reject", "error"]),
        ("synchrony", ["synchronous", "synchronously", "sync", "blocking"], ["asynchronous", "asynchronously", "async", "eventual", "eventually"]),
        ("distance", ["near", "close", "nearby", "local", "closest"], ["far", "distant", "further", "remote"])
    ]

    static let negations: Set<String> = [
        "not", "no", "never", "cannot", "cant", "can't", "dont", "don't", "doesnt", "doesn't", "isnt", "isn't",
        "arent", "aren't", "wont", "won't", "wouldnt", "wouldn't", "shouldnt", "shouldn't", "mustnt", "mustn't",
        "didnt", "didn't", "wasnt", "wasn't", "werent", "weren't", "hasnt", "hasn't", "havent", "haven't",
        "neither", "nor", "none", "nothing", "nobody", "n't"
    ]
    static let universals: Set<String> = [
        "always", "never", "every", "all", "everything", "nothing", "anything", "everyone", "entirely",
        "completely", "impossible", "guaranteed", "whatever", "any"
    ]
    static let hedges: Set<String> = [
        "can", "may", "might", "could", "often", "usually", "sometimes", "typically", "generally", "particular",
        "certain", "some", "specific", "when", "if", "unless", "most", "many", "mostly", "likely", "rarely", "uncommon"
    ]
    /// Replaced before tokenising, in both learner and source text.
    static let phrases: [(String, String)] = [
        ("saves you from", "avoids"), ("save you from", "avoid"), ("saving you from", "avoiding"),
        ("takes load off", "reduces load on"), ("take load off", "reduce load on"),
        ("gives back", "returns"), ("give back", "return"),
        ("turn it back into", "recover"), ("turned back into", "recovered"), ("turn back into", "recover"), ("turns back into", "recovers"),
        ("right away", "immediately"), ("at once", "immediately"),
        ("go stale", "become stale"), ("goes stale", "becomes stale"), ("out of date", "stale"),
        ("one direction only", "one-way"), ("in one direction", "one-way"), ("one way", "one-way"),
        ("is stuck", "cannot proceed"), ("are stuck", "cannot proceed"), ("get stuck", "cannot proceed"), ("both stuck", "cannot proceed"),
        ("which item is which", "item identity"), ("which one is which", "identity"), ("which is which", "identity"),
        ("tell apart", "distinguish"), ("at most once", "at-most-once"), ("more than once", "repeatedly"),
        ("again and again", "repeatedly"), ("over and over", "repeatedly"), ("at the same time", "concurrently"),
        ("in parallel", "concurrently"), ("all or nothing", "atomic"),
        ("roll back", "rollback"), ("rolls back", "rollback"), ("rolled back", "rollback"), ("rolling back", "rollback"),
        ("look up", "lookup"), ("looks up", "lookup"), ("speed up", "accelerate"), ("speeds up", "accelerates"),
        ("sped up", "accelerated"), ("curly braces", "block braces"), ("key=value", "key-value"), ("key value", "key-value"),
        ("times out", "timeout"), ("time out", "timeout"), ("around the world", "worldwide"),
        ("real data", "underlying truth"), ("take in", "receive"), ("hand back", "return"),
        ("have to", "need to"), ("has to", "needs to"), ("had to", "needed to"), ("must be", "need to be")
    ]
    static let irregulars: [String: String] = [
        "is": "be", "are": "be", "was": "be", "were": "be", "been": "be", "being": "be", "am": "be",
        "has": "have", "had": "have", "having": "have", "does": "do", "did": "do", "done": "do", "doing": "do",
        "made": "make", "kept": "keep", "held": "hold", "built": "build", "went": "go", "gone": "go",
        "gave": "give", "given": "give", "took": "take", "taken": "take", "thought": "think", "told": "tell",
        "found": "find", "left": "leave", "sent": "send", "brought": "bring", "caught": "catch", "wrote": "write",
        "written": "write", "chose": "choose", "chosen": "choose", "seen": "see", "saw": "see", "known": "know",
        "knew": "know", "shown": "show", "grew": "grow", "grown": "grow", "ran": "run", "broke": "break",
        "broken": "break", "lost": "lose", "meant": "mean", "hid": "hide", "hidden": "hide", "froze": "freeze",
        "frozen": "freeze", "children": "child", "indices": "index", "data": "data", "criteria": "criterion",
        "better": "good", "best": "good", "worse": "bad", "worst": "bad", "faster": "fast", "slower": "slow",
        "larger": "large", "smaller": "small", "bigger": "big", "cheaper": "cheap",
        "easier": "easy", "harder": "hard", "simpler": "simple", "safer": "safe", "quicker": "quick"
    ]
    static let lyExceptions: Set<String> = ["apply", "reply", "supply", "rely", "multiply", "assembly", "family", "only", "early", "fly", "belly", "anomaly", "italy"]
}
