#!/usr/bin/env python3
"""Authors the golden intelligence corpus.

The content below is hand-curated, not scraped and not generated by a model.
Each atom is a claim a mid-level engineering study source would actually make,
written so that subject/object phrases chain together the way the mechanism
graph expects. Running this script rewrites golden-corpus.json next to it.
"""
import json
import pathlib

DOCS = [
    ("mobile-mastery", "JavaScript Mid-Level Interview Mobile Mastery", "primary study PDF"),
    ("react-notes", "React Rendering Notes", "second source, overlaps on identity/keys"),
    ("http-caching-guide", "HTTP Caching Guide", "second source, overlaps on caching"),
    ("reliability-handbook", "Reliability Handbook", "second source, overlaps on retries/idempotency"),
    ("db-performance", "Database Performance Primer", "indexes, queries, performance"),
]

# (key, doc, page, role, claimType, subject, relation, object, conditions, qualifiers, negated, span)
# conditions: list of (text, isPositive); qualifiers: list of (kind, text)
A = []
def atom(key, doc, page, role, ct, s, r, o, conds=(), quals=(), neg=False, span=None):
    A.append(dict(key=key, doc=doc, page=page, role=role, claimType=ct, subject=s,
                  relation=r, object=o,
                  conditions=[{"text": c, "isPositive": p} for c, p in conds],
                  qualifiers=[{"kind": k, "text": t} for k, t in quals],
                  isNegated=neg,
                  span=span or f"{s} {r} {o}."))

# ---------------------------------------------------------------- React keys
atom("key.def", "mobile-mastery", 12, "compactExplanation", "definition",
     "a key", "explains", "an identifier React uses for a list item",
     span="A key is an identifier React uses for a list item.")
atom("key.enables.identity", "mobile-mastery", 12, "compactExplanation", "mechanism",
     "a stable key", "enables", "identity matching across renders",
     span="A stable key helps React match an item to its previous instance across renders.")
atom("identity.enables.state", "mobile-mastery", 12, "compactExplanation", "mechanism",
     "identity matching across renders", "enables", "state preservation during reorder",
     span="Matching an item to its previous instance preserves that item's state during a reorder.")
atom("state.requires.identity", "react-notes", 3, "explanation", "prerequisite",
     "state preservation during reorder", "requires", "identity matching across renders",
     span="Preserving state during a reorder requires matching each item to its previous instance.")
atom("identity.requires.key", "react-notes", 3, "explanation", "prerequisite",
     "identity matching across renders", "requires", "a stable key",
     span="Matching across renders requires a stable key.")
atom("indexkey.causes.wrongidentity", "mobile-mastery", 13, "caution", "cause",
     "an index key", "causes", "wrong identity correspondence",
     conds=(("the list is reordered", True),),
     span="If the list is reordered, an index key causes wrong identity correspondence.")
atom("wrongidentity.causes.association", "mobile-mastery", 13, "caution", "cause",
     "wrong identity correspondence", "causes", "component instance association changes",
     span="Wrong identity correspondence causes component instance association to change.")
atom("association.causes.statebleed", "mobile-mastery", 13, "caution", "failureMode",
     "component instance association changes", "causes", "state appearing attached to another item",
     span="When the component instance association changes, state may appear attached to another item.")
atom("key.constraint.unique", "react-notes", 4, "explanation", "constraint",
     "a key", "must be", "unique among siblings",
     span="A key must be unique among siblings.")
atom("key.example.id", "mobile-mastery", 13, "example", "example",
     "a database id", "is an example of", "a stable key",
     span="A database id is an example of a stable key.")
atom("reconciliation.def", "react-notes", 2, "explanation", "definition",
     "reconciliation", "explains", "how React compares the new tree with the previous tree",
     span="Reconciliation is how React compares the new tree with the previous tree.")
atom("reconciliation.requires.identity", "react-notes", 2, "explanation", "prerequisite",
     "reconciliation", "requires", "identity matching across renders",
     span="Reconciliation requires matching each element to its previous instance.")

# ------------------------------------------------------------------ Caching
atom("cache.def", "mobile-mastery", 30, "compactExplanation", "definition",
     "caching", "explains", "reuse of previously fetched data",
     span="Caching is the reuse of previously fetched data.")
atom("cache.enables.latency", "mobile-mastery", 30, "compactExplanation", "mechanism",
     "caching", "enables", "lower latency on repeat requests",
     span="Caching enables lower latency on repeat requests.")
atom("latency.enables.throughput", "db-performance", 9, "explanation", "mechanism",
     "lower latency on repeat requests", "enables", "higher throughput under load",
     span="Lower latency on repeat requests enables higher throughput under load.")
atom("cache.requires.lookup", "http-caching-guide", 5, "explanation", "prerequisite",
     "caching", "requires", "a cache lookup before the request",
     span="Caching requires a cache lookup before the request is made.")
atom("lookup.sequence", "http-caching-guide", 5, "explanation", "sequence",
     "a cache lookup", "causes", "either a cached result or a fetch",
     span="A cache lookup produces either a cached result or a fetch.")
atom("cache.failure.stale", "mobile-mastery", 31, "caution", "failureMode",
     "caching", "causes", "stale data",
     conds=(("the underlying data changes", True),),
     span="If the underlying data changes, caching causes stale data.")
atom("cache.tradeoff", "mobile-mastery", 31, "explanation", "tradeoff",
     "caching", "trades off", "freshness against latency",
     span="Caching trades off freshness against latency.")
atom("ttl.prevents.stale", "http-caching-guide", 6, "explanation", "consequence",
     "a short time to live", "prevents", "stale data",
     span="A short time to live prevents stale data.")
atom("ttl.causes.misses", "http-caching-guide", 6, "caution", "consequence",
     "a short time to live", "causes", "more cache misses",
     span="A short time to live causes more cache misses.")
atom("maxage.def", "http-caching-guide", 7, "explanation", "definition",
     "`Cache-Control`", "explains", "how long a response may be reused",
     span="`Cache-Control` states how long a response may be reused.")
atom("maxage.number", "http-caching-guide", 7, "explanation", "constraint",
     "a max-age of 60 seconds", "explains", "one minute of reuse",
     span="A max-age of 60 seconds allows one minute of reuse.")
atom("memoization.sameprinciple", "mobile-mastery", 32, "explanation", "example",
     "memoization", "is an example of", "caching",
     span="Memoization is an example of caching.")
atom("etag.enables.revalidate", "http-caching-guide", 8, "explanation", "mechanism",
     "an `ETag`", "enables", "revalidation without re-sending the body",
     span="An `ETag` enables revalidation without re-sending the body.")

# ------------------------------------------------------------------ Retries
atom("retry.def", "mobile-mastery", 44, "compactExplanation", "definition",
     "a retry", "explains", "another attempt at the same operation",
     span="A retry is another attempt at the same operation.")
atom("retry.enables.success", "mobile-mastery", 44, "compactExplanation", "mechanism",
     "retrying", "enables", "the operation to succeed",
     conds=(("the failure is transient", True),),
     span="If the failure is transient, retrying enables the operation to succeed.")
atom("retry.permanent.failure", "mobile-mastery", 45, "caution", "failureMode",
     "retrying a permanent validation error", "causes", "the same invalid request",
     span="Retrying a permanent validation error causes the same invalid request.")
atom("invalidrequest.causes.repeatfailure", "mobile-mastery", 45, "caution", "cause",
     "the same invalid request", "causes", "repeated failure",
     span="The same invalid request causes repeated failure.")
atom("retry.requires.idempotency", "reliability-handbook", 11, "explanation", "prerequisite",
     "safe retrying", "requires", "an idempotent operation",
     span="Safe retrying requires an idempotent operation.")
atom("retry.tradeoff", "reliability-handbook", 11, "explanation", "tradeoff",
     "retrying", "trades off", "recovery against extra load",
     span="Retrying trades off recovery against extra load.")
atom("backoff.prevents.overload", "reliability-handbook", 12, "explanation", "consequence",
     "exponential backoff", "prevents", "retry storms",
     span="Exponential backoff prevents retry storms.")
atom("retrystorm.causes.outage", "reliability-handbook", 12, "caution", "cause",
     "retry storms", "causes", "sustained overload of the dependency",
     span="Retry storms cause sustained overload of the dependency.")
atom("retry.scope", "reliability-handbook", 11, "explanation", "constraint",
     "retrying", "only applies to", "transient failures",
     quals=(("scope", "transient failures"),),
     span="Retrying only applies to transient failures.")
atom("retry.limit.number", "reliability-handbook", 13, "explanation", "constraint",
     "a retry budget", "must be", "at most 3 attempts",
     span="A retry budget must be at most 3 attempts.")

# -------------------------------------------------------------- Idempotency
atom("idempotent.def", "reliability-handbook", 14, "compactExplanation", "definition",
     "an idempotent operation", "explains", "an operation with the same result when repeated",
     span="An idempotent operation is one with the same result when repeated.")
atom("idempotent.enables.saferetry", "reliability-handbook", 14, "compactExplanation", "mechanism",
     "an idempotent operation", "enables", "safe retrying",
     span="An idempotent operation enables safe retrying.")
atom("idempotencykey.enables.dedup", "reliability-handbook", 15, "explanation", "mechanism",
     "an idempotency key", "enables", "duplicate request detection",
     span="An idempotency key enables duplicate request detection.")
atom("dedup.prevents.doublecharge", "reliability-handbook", 15, "explanation", "consequence",
     "duplicate request detection", "prevents", "a double charge",
     span="Duplicate request detection prevents a double charge.")
atom("put.example", "reliability-handbook", 14, "example", "example",
     "a PUT that sets a field to a fixed value", "is an example of", "an idempotent operation",
     span="A PUT that sets a field to a fixed value is an example of an idempotent operation.")
atom("post.notidempotent", "reliability-handbook", 14, "caution", "constraint",
     "a plain POST", "is", "not idempotent", neg=True,
     span="A plain POST is not idempotent.")

# ---------------------------------------------------------------- HTTP basics
atom("status409.def", "http-caching-guide", 12, "explanation", "definition",
     "409", "explains", "a conflict with the current state",
     span="409 means a conflict with the current state.")
atom("status503.def", "reliability-handbook", 16, "explanation", "definition",
     "503", "explains", "a temporarily unavailable dependency",
     span="503 means a temporarily unavailable dependency.")
atom("status503.enables.retry", "reliability-handbook", 16, "explanation", "mechanism",
     "503", "enables", "a retry with backoff",
     span="A 503 enables a retry with backoff.")
atom("status400.prevents.retry", "reliability-handbook", 16, "caution", "constraint",
     "400", "prevents", "a useful retry",
     span="A 400 prevents a useful retry.")

# ----------------------------------------------------------- DB and indexes
atom("index.def", "db-performance", 3, "compactExplanation", "definition",
     "an index", "explains", "a structure that finds rows without scanning",
     span="An index is a structure that finds rows without scanning the table.")
atom("index.enables.lookup", "db-performance", 3, "compactExplanation", "mechanism",
     "an index", "enables", "row lookup without a full scan",
     span="An index enables row lookup without a full scan.")
atom("lookup.enables.latency", "db-performance", 3, "explanation", "mechanism",
     "row lookup without a full scan", "enables", "lower query latency",
     span="Row lookup without a full scan enables lower query latency.")
atom("index.tradeoff", "db-performance", 4, "explanation", "tradeoff",
     "an index", "trades off", "read speed against write cost",
     span="An index trades off read speed against write cost.")
atom("index.causes.writecost", "db-performance", 4, "caution", "cause",
     "an index", "causes", "extra work on every write",
     span="An index causes extra work on every write.")
atom("index.requires.selectivity", "db-performance", 5, "explanation", "prerequisite",
     "a useful index", "requires", "a selective column",
     span="A useful index requires a selective column.")
atom("lowselectivity.failure", "db-performance", 5, "caution", "failureMode",
     "an index on a low selectivity column", "causes", "the planner ignoring the index",
     span="An index on a low selectivity column causes the planner to ignore the index.")
atom("composite.constraint", "db-performance", 6, "explanation", "constraint",
     "a composite index", "only applies to", "queries that use its leading column",
     quals=(("scope", "queries that use its leading column"),),
     span="A composite index only applies to queries that use its leading column.")
atom("nplusone.def", "db-performance", 7, "caution", "failureMode",
     "an n plus one query", "causes", "one query per row",
     span="An n plus one query causes one query per row.")
atom("nplusone.causes.latency", "db-performance", 7, "caution", "cause",
     "one query per row", "causes", "high total query latency",
     span="One query per row causes high total query latency.")
atom("batching.prevents.nplusone", "db-performance", 7, "explanation", "consequence",
     "batching the lookups", "prevents", "one query per row",
     span="Batching the lookups prevents one query per row.")

# -------------------------------------------------------------- JavaScript
atom("closure.def", "mobile-mastery", 4, "compactExplanation", "definition",
     "a closure", "explains", "a function together with the scope it captured",
     span="A closure is a function together with the scope it captured.")
atom("closure.enables.privatestate", "mobile-mastery", 4, "compactExplanation", "mechanism",
     "a closure", "enables", "private state without a class",
     span="A closure enables private state without a class.")
atom("closure.causes.retention", "mobile-mastery", 5, "caution", "failureMode",
     "a closure over a large object", "causes", "memory retention",
     span="A closure over a large object causes memory retention.")
atom("js.def", "mobile-mastery", 3, "compactExplanation", "definition",
     "JavaScript", "explains", "a single threaded language with an event loop",
     span="JavaScript is a single threaded language with an event loop.")
atom("http.def", "http-caching-guide", 1, "explanation", "definition",
     "HTTP", "explains", "a request response protocol",
     span="HTTP is a request response protocol.")
atom("eventloop.def", "mobile-mastery", 6, "compactExplanation", "definition",
     "the event loop", "explains", "the order in which queued work runs",
     span="The event loop is the order in which queued work runs.")
atom("microtask.sequence", "mobile-mastery", 6, "explanation", "sequence",
     "a microtask", "is required for", "running before the next macrotask",
     span="A microtask is required for running before the next macrotask.")
atom("promise.enables.async", "mobile-mastery", 7, "compactExplanation", "mechanism",
     "a promise", "enables", "sequencing asynchronous work",
     span="A promise enables sequencing asynchronous work.")
atom("await.requires.async", "mobile-mastery", 7, "explanation", "prerequisite",
     "`await`", "requires", "an async function",
     span="`await` requires an async function.")
atom("hoisting.def", "mobile-mastery", 8, "explanation", "definition",
     "hoisting", "explains", "declarations being processed before execution",
     span="Hoisting is declarations being processed before execution.")
atom("letconst.contrast", "mobile-mastery", 8, "explanation", "distinction",
     "`let`", "differs from", "`var` in block scoping",
     span="`let` differs from `var` in block scoping.")
atom("equality.contrast", "mobile-mastery", 9, "explanation", "distinction",
     "strict equality", "differs from", "loose equality by skipping coercion",
     span="Strict equality differs from loose equality by skipping coercion.")
atom("debounce.def", "mobile-mastery", 10, "explanation", "definition",
     "debouncing", "explains", "delaying work until input stops",
     span="Debouncing is delaying work until input stops.")
atom("debounce.prevents.work", "mobile-mastery", 10, "explanation", "consequence",
     "debouncing", "prevents", "repeated work on every keystroke",
     span="Debouncing prevents repeated work on every keystroke.")

# ------------------------------------------------------- React performance
atom("memo.def", "react-notes", 6, "explanation", "definition",
     "`useMemo`", "explains", "caching a computed value between renders",
     span="`useMemo` is caching a computed value between renders.")
atom("memo.sameprinciple", "react-notes", 6, "explanation", "example",
     "`useMemo`", "is an example of", "caching",
     span="`useMemo` is an example of caching.")
atom("memo.requires.stabledeps", "react-notes", 6, "explanation", "prerequisite",
     "`useMemo`", "requires", "stable dependencies",
     span="`useMemo` requires stable dependencies.")
atom("unstabledeps.failure", "react-notes", 7, "caution", "failureMode",
     "unstable dependencies", "causes", "recomputation on every render",
     span="Unstable dependencies cause recomputation on every render.")
atom("recompute.causes.jank", "react-notes", 7, "caution", "cause",
     "recomputation on every render", "causes", "dropped frames",
     span="Recomputation on every render causes dropped frames.")
atom("rerender.requires.statechange", "react-notes", 5, "explanation", "prerequisite",
     "a re-render", "requires", "a state or prop change",
     span="A re-render requires a state or prop change.")
atom("virtualdom.def", "react-notes", 2, "explanation", "definition",
     "the virtual tree", "explains", "an in-memory description of the UI",
     span="The virtual tree is an in-memory description of the UI.")

# ----------------------------------------------------- Distributed systems
atom("timeout.def", "reliability-handbook", 20, "compactExplanation", "definition",
     "a timeout", "explains", "an upper bound on waiting",
     span="A timeout is an upper bound on waiting.")
atom("timeout.prevents.threadexhaustion", "reliability-handbook", 20, "explanation", "consequence",
     "a timeout", "prevents", "thread pool exhaustion",
     span="A timeout prevents thread pool exhaustion.")
atom("nolimit.causes.exhaustion", "reliability-handbook", 20, "caution", "cause",
     "an unbounded wait", "causes", "thread pool exhaustion",
     span="An unbounded wait causes thread pool exhaustion.")
atom("exhaustion.causes.cascade", "reliability-handbook", 21, "caution", "cause",
     "thread pool exhaustion", "causes", "a cascading failure",
     span="Thread pool exhaustion causes a cascading failure.")
atom("breaker.def", "reliability-handbook", 22, "explanation", "definition",
     "a circuit breaker", "explains", "a switch that stops calls to a failing dependency",
     span="A circuit breaker is a switch that stops calls to a failing dependency.")
atom("breaker.prevents.cascade", "reliability-handbook", 22, "explanation", "consequence",
     "a circuit breaker", "prevents", "a cascading failure",
     span="A circuit breaker prevents a cascading failure.")
atom("breaker.requires.healthsignal", "reliability-handbook", 22, "explanation", "prerequisite",
     "a circuit breaker", "requires", "a health signal",
     span="A circuit breaker requires a health signal.")
atom("queue.enables.smoothing", "reliability-handbook", 23, "explanation", "mechanism",
     "a queue", "enables", "smoothing of bursty load",
     span="A queue enables smoothing of bursty load.")
atom("queue.causes.latency", "reliability-handbook", 23, "caution", "consequence",
     "a queue", "causes", "added end to end latency",
     span="A queue causes added end to end latency.")
atom("atleastonce.requires.idempotency", "reliability-handbook", 24, "explanation", "prerequisite",
     "at least once delivery", "requires", "an idempotent operation",
     span="At least once delivery requires an idempotent operation.")
atom("atleastonce.causes.duplicates", "reliability-handbook", 24, "explanation", "cause",
     "at least once delivery", "causes", "duplicate messages",
     span="At least once delivery causes duplicate messages.")
atom("duplicates.causes.doublecharge", "reliability-handbook", 24, "caution", "failureMode",
     "duplicate messages", "causes", "a double charge",
     conds=(("the handler is not idempotent", True),),
     span="If the handler is not idempotent, duplicate messages cause a double charge.")

# ------------------------------------------------------------- Performance
atom("profile.requires.measurement", "db-performance", 10, "explanation", "prerequisite",
     "useful optimisation", "requires", "a measurement first",
     span="Useful optimisation requires a measurement first.")
atom("guessing.failure", "db-performance", 10, "caution", "failureMode",
     "optimising without measurement", "causes", "effort spent off the hot path",
     span="Optimising without measurement causes effort spent off the hot path.")
atom("p99.def", "db-performance", 11, "explanation", "definition",
     "the p99 latency", "explains", "the slowest one percent of requests",
     span="The p99 latency is the slowest one percent of requests.")
atom("p99.contrast", "db-performance", 11, "explanation", "distinction",
     "the p99 latency", "differs from", "the average latency",
     span="The p99 latency differs from the average latency.")
atom("pagination.prevents.largepayload", "db-performance", 12, "explanation", "consequence",
     "pagination", "prevents", "a very large payload",
     span="Pagination prevents a very large payload.")
atom("largepayload.causes.latency", "db-performance", 12, "caution", "cause",
     "a very large payload", "causes", "high total query latency",
     span="A very large payload causes high total query latency.")
atom("connectionpool.enables.reuse", "db-performance", 13, "explanation", "mechanism",
     "a connection pool", "enables", "reuse of open connections",
     span="A connection pool enables reuse of open connections.")
atom("reuse.enables.latency", "db-performance", 13, "explanation", "mechanism",
     "reuse of open connections", "enables", "lower query latency",
     span="Reuse of open connections enables lower query latency.")

# --------------------------------------------- Non-factual roles (negative)
atom("mnemonic.keys", "mobile-mastery", 12, "mnemonic", "definition",
     "keys", "explains", "keep your identity",
     span="Keys keep your identity.")
atom("interview.retry", "mobile-mastery", 45, "presentationAdvice", "definition",
     "you", "should be", "clear that retries need idempotency",
     span="Say that retries need idempotency.")
atom("footer", "mobile-mastery", 45, "furniture", "definition",
     "page", "is", "45",
     span="Page 45")

# Cross-source overlap: same claim, different wording, different documents.
atom("cache.def.alt", "http-caching-guide", 2, "compactExplanation", "definition",
     "caching", "explains", "reuse of data fetched earlier",
     span="Caching is the reuse of data fetched earlier.")
atom("retry.enables.success.alt", "reliability-handbook", 10, "compactExplanation", "mechanism",
     "retrying", "enables", "the operation to succeed",
     span="Retrying enables the operation to succeed.")
atom("index.enables.lookup.alt", "mobile-mastery", 50, "explanation", "mechanism",
     "an index", "enables", "row lookup without a full scan",
     span="An index enables row lookup without a full scan.")
atom("key.enables.identity.alt", "react-notes", 3, "compactExplanation", "mechanism",
     "a stable key", "enables", "identity matching across renders",
     span="A stable key enables identity matching across renders.")
atom("cache.stale.contra", "http-caching-guide", 9, "explanation", "consequence",
     "caching", "prevents", "stale data",
     span="Caching prevents stale data.")
atom("idempotent.def.alt", "mobile-mastery", 46, "explanation", "definition",
     "an idempotent operation", "explains", "an operation with the same result when repeated",
     span="An idempotent operation is one with the same result when repeated.")
atom("timeout.def.alt", "mobile-mastery", 47, "explanation", "definition",
     "a timeout", "explains", "an upper bound on waiting",
     span="A timeout is an upper bound on waiting.")
atom("breaker.def.alt", "mobile-mastery", 48, "explanation", "definition",
     "a circuit breaker", "explains", "a switch that stops calls to a failing dependency",
     span="A circuit breaker is a switch that stops calls to a failing dependency.")
atom("retry.limit.number.alt", "mobile-mastery", 49, "explanation", "constraint",
     "a retry budget", "must be", "at most 5 attempts",
     span="A retry budget must be at most 5 attempts.")

# --------------------------------------------------------------- Chains (30)
CHAINS = [
    ("chain.key.state", "a stable key",
     ["a stable key", "identity matching across renders", "state preservation during reorder"]),
    ("chain.indexkey.bleed", "an index key",
     ["an index key", "wrong identity correspondence", "component instance association changes",
      "state appearing attached to another item"]),
    ("chain.cache.throughput", "caching",
     ["caching", "lower latency on repeat requests", "higher throughput under load"]),
    ("chain.retry.success", "retrying", ["retrying", "the operation to succeed"]),
    ("chain.retry.permanent", "retrying a permanent validation error",
     ["retrying a permanent validation error", "the same invalid request", "repeated failure"]),
    ("chain.index.latency", "an index",
     ["an index", "row lookup without a full scan", "lower query latency"]),
    ("chain.nplusone", "an n plus one query",
     ["an n plus one query", "one query per row", "high total query latency"]),
    ("chain.unbounded.cascade", "an unbounded wait",
     ["an unbounded wait", "thread pool exhaustion", "a cascading failure"]),
    ("chain.atleastonce", "at least once delivery",
     ["at least once delivery", "duplicate messages", "a double charge"]),
    ("chain.unstabledeps", "unstable dependencies",
     ["unstable dependencies", "recomputation on every render", "dropped frames"]),
    ("chain.retrystorm", "retry storms",
     ["retry storms", "sustained overload of the dependency"]),
    ("chain.idempotent.retry", "an idempotent operation",
     ["an idempotent operation", "safe retrying"]),
    ("chain.idempotencykey", "an idempotency key",
     ["an idempotency key", "duplicate request detection", "a double charge"]),
    ("chain.connectionpool", "a connection pool",
     ["a connection pool", "reuse of open connections", "lower query latency"]),
    ("chain.closure.state", "a closure", ["a closure", "private state without a class"]),
    ("chain.closure.retention", "a closure over a large object",
     ["a closure over a large object", "memory retention"]),
    ("chain.promise", "a promise", ["a promise", "sequencing asynchronous work"]),
    ("chain.debounce", "debouncing", ["debouncing", "repeated work on every keystroke"]),
    ("chain.ttl.miss", "a short time to live", ["a short time to live", "more cache misses"]),
    ("chain.ttl.stale", "a short time to live", ["a short time to live", "stale data"]),
    ("chain.cache.stale", "caching", ["caching", "stale data"]),
    ("chain.etag", "an `ETag`", ["an `ETag`", "revalidation without re-sending the body"]),
    ("chain.lowselectivity", "an index on a low selectivity column",
     ["an index on a low selectivity column", "the planner ignoring the index"]),
    ("chain.index.write", "an index", ["an index", "extra work on every write"]),
    ("chain.breaker", "a circuit breaker", ["a circuit breaker", "a cascading failure"]),
    ("chain.timeout", "a timeout", ["a timeout", "thread pool exhaustion"]),
    ("chain.queue.smoothing", "a queue", ["a queue", "smoothing of bursty load"]),
    ("chain.queue.latency", "a queue", ["a queue", "added end to end latency"]),
    ("chain.largepayload", "a very large payload", ["a very large payload", "high total query latency"]),
    ("chain.guessing", "optimising without measurement",
     ["optimising without measurement", "effort spent off the hot path"]),
    ("chain.503.retry", "503", ["503", "a retry with backoff"]),
    ("chain.memo.recompute", "unstable dependencies",
     ["unstable dependencies", "recomputation on every render"]),
]

# ------------------------------------------------------ Learner cases (90+)
L = []
def learner(key, concept, text, verdict, misconceptions=(), note=""):
    L.append(dict(key=key, concept=concept, text=text, expectedVerdict=verdict,
                  expectedMisconceptions=list(misconceptions), note=note))

# 20 paraphrases -> supported
PARAPHRASES = [
    ("para.cache", "caching", "Caching means reusing data you fetched before."),
    ("para.key", "a stable key", "A stable key lets React match an item to its previous instance across renders."),
    ("para.index", "an index", "An index enables looking up rows without scanning the whole table."),
    ("para.idempotent", "an idempotent operation", "An idempotent operation gives the same result when it is repeated."),
    ("para.timeout", "a timeout", "A timeout is an upper bound on how long you wait."),
    ("para.breaker", "a circuit breaker", "A circuit breaker stops calls to a failing dependency."),
    ("para.closure", "a closure", "A closure is a function plus the scope it captured."),
    ("para.promise", "a promise", "A promise enables sequencing asynchronous work."),
    ("para.debounce", "debouncing", "Debouncing delays work until the input stops."),
    ("para.etag", "an `ETag`", "An `ETag` enables revalidation without re-sending the body."),
    ("para.queue", "a queue", "A queue enables smoothing of bursty load."),
    ("para.pool", "a connection pool", "A connection pool enables reuse of open connections."),
    ("para.p99", "the p99 latency", "The p99 latency is the slowest one percent of requests."),
    ("para.nplusone", "an n plus one query", "An n plus one query causes one query per row."),
    ("para.backoff", "exponential backoff", "Exponential backoff prevents retry storms."),
    ("para.dedup", "duplicate request detection", "Duplicate request detection prevents a double charge."),
    ("para.memo", "`useMemo`", "`useMemo` requires stable dependencies."),
    ("para.rerender", "a re-render", "A re-render requires a state or prop change."),
    ("para.batching", "batching the lookups", "Batching the lookups prevents one query per row."),
    ("para.pagination", "pagination", "Pagination prevents a very large payload."),
]
for key, concept, text in PARAPHRASES:
    learner(key, concept, text, "supported", note="paraphrase of a source claim")

# 20 contradictions
CONTRADICTIONS = [
    ("contra.retry.reverse", "retrying", "The operation succeeding causes the retry.", ["reversedCauseEffect"]),
    ("contra.key.reverse", "a stable key", "Identity matching across renders enables a stable key.", ["reversedCauseEffect"]),
    ("contra.cache.negation", "caching", "Caching does not enable lower latency on repeat requests.", ["incorrectNegation"]),
    ("contra.index.negation", "an index", "An index does not enable row lookup without a full scan.", ["incorrectNegation"]),
    ("contra.timeout.negation", "a timeout", "A timeout does not prevent thread pool exhaustion.", ["incorrectNegation"]),
    ("contra.idempotent.dependency", "safe retrying", "An idempotent operation requires safe retrying.", ["reversedCauseEffect"]),
    ("contra.memo.dependency", "`useMemo`", "Stable dependencies require `useMemo`.", ["reversedCauseEffect"]),
    ("contra.breaker.negation", "a circuit breaker", "A circuit breaker does not prevent a cascading failure.", ["incorrectNegation"]),
    ("contra.retrybudget.number", "a retry budget", "A retry budget must be at most 10 attempts.", ["numericalMismatch"]),
    ("contra.maxage.number", "a max-age of 60 seconds", "A max-age of 600 seconds allows one minute of reuse.", ["numericalMismatch"]),
    ("contra.nplusone.reverse", "an n plus one query", "One query per row causes an n plus one query.", ["reversedCauseEffect"]),
    ("contra.exhaustion.reverse", "thread pool exhaustion", "A cascading failure causes thread pool exhaustion.", ["reversedCauseEffect"]),
    ("contra.queue.negation", "a queue", "A queue does not cause added end to end latency.", ["incorrectNegation"]),
    ("contra.index.write.negation", "an index", "An index does not cause extra work on every write.", ["incorrectNegation"]),
    ("contra.closure.reverse", "a closure", "Private state without a class enables a closure.", ["reversedCauseEffect"]),
    ("contra.duplicates.reverse", "at least once delivery", "Duplicate messages cause at least once delivery.", ["reversedCauseEffect"]),
    ("contra.batching.negation", "batching the lookups", "Batching the lookups does not prevent one query per row.", ["incorrectNegation"]),
    ("contra.ttl.negation", "a short time to live", "A short time to live does not cause more cache misses.", ["incorrectNegation"]),
    ("contra.pool.reverse", "a connection pool", "Reuse of open connections enables a connection pool.", ["reversedCauseEffect"]),
    ("contra.pagination.negation", "pagination", "Pagination does not prevent a very large payload.", ["incorrectNegation"]),
]
for key, concept, text, misc in CONTRADICTIONS:
    learner(key, concept, text, "contradicted", misc, note="contradicts a source claim")

# 20 overgeneralisations
OVERGENERALISATIONS = [
    ("over.retry.every", "retrying", "You should always retry every failed request."),
    ("over.retry.all", "retrying", "Retrying always enables the operation to succeed."),
    ("over.cache.always", "caching", "Caching always causes stale data."),
    ("over.index.every", "an index", "Every column should have an index."),
    ("over.composite.any", "a composite index", "A composite index applies to any query."),
    ("over.idempotent.all", "an idempotent operation", "All operations are idempotent."),
    ("over.duplicates.always", "duplicate messages", "Duplicate messages always cause a double charge."),
    ("over.key.always", "a key", "A key is always unique."),
    ("over.timeout.every", "a timeout", "Every wait must have a timeout, always."),
    ("over.memo.always", "`useMemo`", "You should always use `useMemo` for every value."),
    ("over.backoff.always", "exponential backoff", "Exponential backoff always prevents every outage."),
    ("over.breaker.every", "a circuit breaker", "Every dependency always needs a circuit breaker."),
    ("over.queue.always", "a queue", "A queue always enables smoothing of bursty load with no cost."),
    ("over.ttl.always", "a short time to live", "A short time to live always prevents stale data."),
    ("over.indexkey.always", "an index key", "An index key always causes wrong identity correspondence."),
    ("over.closure.every", "a closure", "Every closure causes memory retention."),
    ("over.nplusone.always", "an n plus one query", "Every query causes one query per row."),
    ("over.profile.never", "useful optimisation", "Optimisation never requires a measurement first."),
    ("over.pagination.always", "pagination", "Pagination always prevents high total query latency."),
    ("over.503.always", "503", "Every error code always enables a retry with backoff."),
]
for key, concept, text in OVERGENERALISATIONS:
    learner(key, concept, text, "contradicted", ["scopeTooBroad"], note="overgeneralisation of a restricted claim")

# 30 mixed learner explanations
MIXED = [
    ("mix.retry.partial", "retrying", "Retries fix failed requests.", "partiallySupported", ["missingCondition"]),
    ("mix.cache.partial", "caching", "Caching causes stale data.", "partiallySupported", ["missingCondition"]),
    ("mix.duplicates.partial", "duplicate messages", "Duplicate messages cause a double charge.", "partiallySupported", ["missingCondition"]),
    ("mix.indexkey.partial", "an index key", "An index key causes wrong identity correspondence.", "partiallySupported", ["missingCondition"]),
    ("mix.retry.narrow", "retrying", "If the request is a GET, retrying enables the operation to succeed.", "partiallySupported", ["scopeTooNarrow"]),
    ("mix.cache.addition", "caching", "Caching enables lower latency and guarantees correctness forever.", "partiallySupported", ["unsupportedAddition"]),
    ("mix.index.addition", "an index", "An index enables row lookup and rewrites the query planner.", "partiallySupported", ["unsupportedAddition"]),
    ("mix.unknown.topic", "caching", "Kubernetes pods schedule onto nodes by affinity.", "notAddressed", []),
    ("mix.unknown.topic2", "retrying", "Rust borrows have lifetimes.", "notAddressed", []),
    ("mix.identifier", "`useMemo`", "`useCallback` requires stable dependencies.", "contradicted", ["identifierMismatch"]),
    ("mix.status", "503", "504 means a temporarily unavailable dependency.", "contradicted", ["identifierMismatch"]),
    ("mix.key.supported", "a stable key", "A stable key enables identity matching across renders.", "supported", []),
    ("mix.state.supported", "state preservation during reorder", "State preservation during reorder requires identity matching across renders.", "supported", []),
    ("mix.breaker.supported", "a circuit breaker", "A circuit breaker requires a health signal.", "supported", []),
    ("mix.closure.supported", "a closure over a large object", "A closure over a large object causes memory retention.", "supported", []),
    ("mix.await.supported", "`await`", "`await` requires an async function.", "supported", []),
    ("mix.tradeoff.supported", "caching", "Caching trades off freshness against latency.", "supported", []),
    ("mix.index.tradeoff", "an index", "An index trades off read speed against write cost.", "supported", []),
    ("mix.selectivity.supported", "a useful index", "A useful index requires a selective column.", "supported", []),
    ("mix.storm.supported", "retry storms", "Retry storms cause sustained overload of the dependency.", "supported", []),
    ("mix.exhaustion.supported", "an unbounded wait", "An unbounded wait causes thread pool exhaustion.", "supported", []),
    ("mix.cascade.supported", "thread pool exhaustion", "Thread pool exhaustion causes a cascading failure.", "supported", []),
    ("mix.memo.recompute", "unstable dependencies", "Unstable dependencies cause recomputation on every render.", "supported", []),
    ("mix.jank.supported", "recomputation on every render", "Recomputation on every render causes dropped frames.", "supported", []),
    ("mix.lookup.supported", "row lookup without a full scan", "Row lookup without a full scan enables lower query latency.", "supported", []),
    ("mix.throughput.supported", "lower latency on repeat requests", "Lower latency on repeat requests enables higher throughput under load.", "supported", []),
    ("mix.atleastonce.supported", "at least once delivery", "At least once delivery requires an idempotent operation.", "supported", []),
    ("mix.reuse.supported", "reuse of open connections", "Reuse of open connections enables lower query latency.", "supported", []),
    ("mix.guessing.supported", "optimising without measurement", "Optimising without measurement causes effort spent off the hot path.", "supported", []),
    ("mix.largepayload.supported", "a very large payload", "A very large payload causes high total query latency.", "supported", []),
]
for key, concept, text, verdict, misc in MIXED:
    learner(key, concept, text, verdict, misc, note="mixed learner explanation")

# ------------------------------------------- Cross-source relation candidates
CROSS = [
    ("cross.cache.def", "cache.def", "cache.def.alt", "samePrincipleAs"),
    ("cross.retry.success", "retry.enables.success", "retry.enables.success.alt", "refines"),
    ("cross.index.lookup", "index.enables.lookup", "index.enables.lookup.alt", "samePrincipleAs"),
    ("cross.key.identity", "key.enables.identity", "key.enables.identity.alt", "samePrincipleAs"),
    ("cross.idempotent.def", "idempotent.def", "idempotent.def.alt", "samePrincipleAs"),
    ("cross.timeout.def", "timeout.def", "timeout.def.alt", "samePrincipleAs"),
    ("cross.breaker.def", "breaker.def", "breaker.def.alt", "samePrincipleAs"),
    ("cross.memo.caching", "memo.sameprinciple", "memoization.sameprinciple", "samePrincipleAs"),
    ("cross.retrybudget", "retry.limit.number", "retry.limit.number.alt", "numericConflict"),
    ("cross.cache.stale", "cache.failure.stale", "cache.stale.contra", "directionConflict"),
    ("cross.retry.idempotency", "retry.requires.idempotency", "idempotent.def.alt", "sharedConcept"),
    ("cross.atleastonce.idempotency", "atleastonce.requires.idempotency", "idempotent.def.alt", "sharedConcept"),
    ("cross.timeout.exhaustion", "timeout.prevents.threadexhaustion", "timeout.def.alt", "sharedConcept"),
    ("cross.latency.db.cache", "cache.enables.latency", "lookup.enables.latency", "sharedConcept"),
    ("cross.identity.react", "identity.requires.key", "key.enables.identity", "inverse"),
    ("cross.reconciliation", "reconciliation.requires.identity", "identity.enables.state", "sharedConcept"),
    ("cross.ttl.stale", "ttl.prevents.stale", "cache.failure.stale", "sharedConcept"),
    ("cross.backoff.storm", "backoff.prevents.overload", "retry.permanent.failure", "sharedConcept"),
    ("cross.breaker.cascade", "breaker.prevents.cascade", "breaker.def.alt", "sharedConcept"),
    ("cross.pool.cache", "connectionpool.enables.reuse", "cache.def", "sharedConcept"),
]
CROSS = [dict(key=k, first=a, second=b, expected=kind) for k, a, b, kind in CROSS]

corpus = {
    "schemaVersion": 1,
    "extractionVersion": "leu.extract.1",
    "documents": [{"id": d, "title": t, "note": n} for d, t, n in DOCS],
    "atoms": A,
    "chains": [{"key": k, "start": s, "labels": l} for k, s, l in CHAINS],
    "learnerCases": L,
    "crossSourceCandidates": CROSS,
}

out = pathlib.Path(__file__).resolve().parent.parent / "golden-corpus.json"
out.write_text(json.dumps(corpus, indent=1) + "\n")
print(f"atoms={len(A)} chains={len(CHAINS)} learnerCases={len(L)} cross={len(CROSS)} -> {out}")
